### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by predikament** [rockzt/rockzt#1]
https://github.com/rockzt/rockzt/blob/d072f4d0c0405f62e98218d562d627d53ab0ee2e/README.md?plain=1#L12

_Javacscript_ ![](https://cdn.betterttv.net/emote/5fddff9c22274a347e6bb3fe/1x.webp) .. **Javascript** ![](https://cdn.betterttv.net/emote/5634825b4830ef1d05f8e5c4/1x.webp) 

# .. JavaScript ![](https://cdn.betterttv.net/emote/60fd721e2d1eba5400d17302/1x.webp)

**Comment by rockzt** [comment]
Was on purpose.

Thanks !!!!!
